CLASS zcl_je_created_handler DEFINITION
  PUBLIC ABSTRACT FINAL
  CREATE PUBLIC
  FOR EVENTS OF i_journalentrytp.

PUBLIC SECTION.
PROTECTED SECTION.
PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_JE_CREATED_HANDLER IMPLEMENTATION.
ENDCLASS.
